version: '3.8'
services:
  client:
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    build:
      dockerfile: Dockerfile
      context: ../cnab-app
    ports:
      - "3001:3001"
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
      - CLIENT_ID=YOUR_CLIENT_ID
      - CLIENT_SECRET=YOUR_SECRET
      - CALLBACK_URL=http://localhost:3000/auth/callback
      - HOST=db
      - USER=postgres
      - DATABASE=cnab
      - PASSWORD=admin
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - REDIRECT_URL=http://localhost:3001/
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY0NjgxNTM3MiwiaWF0IjoxNjQ2ODE1MzcyfQ.MEqBTaW5TF7U6ipCpfnLSC_g-x0kAbsCmUf801KJ4HQ
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cnab
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
