version: '3.8'
services:
  client:
    environment:
      - API_URL=api
    build:
      dockerfile: Dockerfile
      context: ./client
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm run nodemon
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DEBUG=nodejs-docker-express:*
      - CLIENT_ID=YOUR_CLIENT_ID
      - CLIENT_SECRET=YOUR_SECRET
      - CALLBACK_URL=http://localhost:3000/auth/callback
      - HOST=db
      - USER=postgres
      - DATABASE=cnab
      - PASSWORD=admin
      - DB_PORT=5432
      - DB_DIALECT=postgres
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cnab
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
